#!/usr/bin/env python3
"""Generate a self-contained deterministic WSC general-DMA probe."""

from __future__ import annotations

import argparse
from pathlib import Path


ROM_SIZE = 64 * 1024
FOOTER_SIZE = 16

# 80186 machine code, entered at F000:0000 by the carrier reset vector:
#   cli
#   mov al,0x80; out 0x60,al   ; enable Color mode before Color-only GDMA
#   mov al,0x00; out 0x40,al   ; source f0100
#   mov al,0x01; out 0x41,al
#   mov al,0x0f; out 0x42,al
#   mov al,0x00; out 0x44,al   ; destination 4000
#   mov al,0x40; out 0x45,al
#   mov al,0x04; out 0x46,al   ; four bytes
#   mov al,0x00; out 0x47,al
#   mov al,0x80; out 0x48,al   ; start, increment
# hang: jmp hang
PROGRAM = bytes(
    (
        0xFA,
        0xB0, 0x80, 0xE6, 0x60,
        0xB0, 0x00, 0xE6, 0x40,
        0xB0, 0x01, 0xE6, 0x41,
        0xB0, 0x0F, 0xE6, 0x42,
        0xB0, 0x00, 0xE6, 0x44,
        0xB0, 0x40, 0xE6, 0x45,
        0xB0, 0x04, 0xE6, 0x46,
        0xB0, 0x00, 0xE6, 0x47,
        0xB0, 0x80, 0xE6, 0x48,
        0xEB, 0xFE,
    )
)


def footer() -> bytes:
    """Return the repository-authored WSC probe footer before checksum."""

    result = bytearray(FOOTER_SIZE)
    result[0:5] = b"\xEA\x00\x00\x00\xF0"  # jmp far F000:0000
    result[5] = 0x00  # Maintenance byte.
    result[6] = 0x00  # Homebrew/test developer ID.
    result[7] = 0x01  # WonderSwan Color required for general DMA.
    result[8] = 0x44  # Repository-authored diagnostic ID.
    result[9] = 0x01  # Fixture format version.
    result[10] = 0x00  # Smallest standard ROM-size encoding.
    result[11] = 0x00  # No save memory.
    result[12] = 0x04  # 16-bit ROM bus, horizontal orientation.
    result[13] = 0x00  # Bandai 2001 mapper.
    return bytes(result)


def image() -> bytes:
    """Construct the deterministic probe image and stamp its footer checksum."""

    result = bytearray((0xFF,)) * ROM_SIZE
    result[: len(PROGRAM)] = PROGRAM
    result[0x0100:0x0104] = bytes((0x34, 0x12, 0x78, 0x56))
    result[-FOOTER_SIZE:] = footer()
    result[-2:] = (sum(result[:-2]) & 0xFFFF).to_bytes(2, "little")
    return bytes(result)


def generate(output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_bytes(image())


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "paths",
        type=Path,
        nargs="+",
        metavar="OUTPUT",
        help="output path; a preceding historical input argument is ignored",
    )
    args = parser.parse_args()

    if len(args.paths) not in (1, 2):
        parser.error("expected OUTPUT or UNUSED_INPUT OUTPUT")
    # Keep the historical two-path command shape working while making the
    # generated bytes completely independent of any input file.
    output_path = args.paths[-1]

    try:
        generate(output_path)
    except (OSError, ValueError) as error:
        raise SystemExit(f"cannot generate {output_path}: {error}") from error
    print(f"generated {output_path} ({ROM_SIZE} bytes)")


if __name__ == "__main__":
    main()
