#!/usr/bin/env python3
"""Generate a self-contained WonderSwan ROM that writes mapper ports."""

from __future__ import annotations

import argparse
from pathlib import Path


ROM_SIZE = 64 * 1024
FOOTER_SIZE = 16

# 80186 machine code, entered at F000:0000 by the carrier reset vector. The
# comments below record the exact reset-to-probe instruction-chain identity and
# physical origin PC expected by the regression verifier for each mapper write.
#   cli
#   mov al, 0x10; out 0xc0, al  # instruction 7,  PC 0xf0003
#   mov al, 0x21; out 0xc1, al  # instruction 9,  PC 0xf0007
#   mov al, 0x32; out 0xc2, al  # instruction 11, PC 0xf000b
#   mov al, 0x43; out 0xc3, al  # instruction 13, PC 0xf000f
#   mov ax, 0x6655
#   out 0xc0, ax                 # instruction 15, PC 0xf0014; C0 then C1
#   mov al, 0x54; out 0xcf, al   # instruction 17, PC 0xf0018
#   mov ax, 0x0103; out 0xd0, ax # instruction 19, PC 0xf001d; D0 low, D1 high
#   mov ax, 0x0204; out 0xd2, ax # instruction 21, PC 0xf0022; D2 low, D3 high
#   mov ax, 0x0305; out 0xd4, ax # instruction 23, PC 0xf0027; D4 low, D5 high
#   mov al, 0x01; out 0xce, al   # instruction 25, PC 0xf002b; self-flash control
# hang: jmp hang
PROGRAM = bytes(
    (
        0xFA,
        0xB0,
        0x10,
        0xE6,
        0xC0,
        0xB0,
        0x21,
        0xE6,
        0xC1,
        0xB0,
        0x32,
        0xE6,
        0xC2,
        0xB0,
        0x43,
        0xE6,
        0xC3,
        0xB8,
        0x55,
        0x66,
        0xE7,
        0xC0,
        0xB0,
        0x54,
        0xE6,
        0xCF,
        0xB8,
        0x03,
        0x01,
        0xE7,
        0xD0,
        0xB8,
        0x04,
        0x02,
        0xE7,
        0xD2,
        0xB8,
        0x05,
        0x03,
        0xE7,
        0xD4,
        0xB0,
        0x01,
        0xE6,
        0xCE,
        0xEB,
        0xFE,
    )
)


def footer() -> bytes:
    """Return the repository-authored mapper-probe footer before checksum."""

    result = bytearray(FOOTER_SIZE)
    result[0:5] = b"\xEA\x00\x00\x00\xF0"  # jmp far F000:0000
    result[5] = 0x00  # Maintenance byte.
    result[6] = 0x00  # Homebrew/test developer ID.
    result[7] = 0x00  # Mono cartridge.
    result[8] = 0x43  # Repository-authored diagnostic ID.
    result[9] = 0x01  # Fixture format version.
    result[10] = 0x00  # Smallest standard ROM-size encoding.
    result[11] = 0x00  # No save memory.
    result[12] = 0x04  # 16-bit ROM bus, horizontal orientation.
    result[13] = 0x01  # Bandai 2003 mapper / RTC selector.
    return bytes(result)


def image() -> bytes:
    """Construct the deterministic probe image and stamp its footer checksum."""

    result = bytearray((0xFF,)) * ROM_SIZE
    result[: len(PROGRAM)] = PROGRAM
    result[-FOOTER_SIZE:] = footer()
    result[-2:] = (sum(result[:-2]) & 0xFFFF).to_bytes(2, "little")
    return bytes(result)


def generate(output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_bytes(image())


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "paths",
        type=Path,
        nargs="+",
        metavar="OUTPUT",
        help="output path; a preceding historical input argument is ignored",
    )
    args = parser.parse_args()

    if len(args.paths) not in (1, 2):
        parser.error("expected OUTPUT or UNUSED_INPUT OUTPUT")
    # Keep the historical two-path command shape working while making the
    # generated bytes completely independent of any input file.
    output_path = args.paths[-1]

    try:
        generate(output_path)
    except (OSError, ValueError) as error:
        raise SystemExit(f"cannot generate {output_path}: {error}") from error

    print(f"generated {output_path} ({ROM_SIZE} bytes)")


if __name__ == "__main__":
    main()
