#!/usr/bin/env python3
"""Verify clean-room WSC window-boundary ROMs and stable RGB captures.

This oracle is intentionally independent of the generator.  It pins each ROM
identity, reconstructs the expected 224x144 composition from the documented
inclusive rectangle, checks named boundary samples before the whole frame, and
accepts an explicit ROM/frame pair so regression integration cannot guess paths.
"""

from __future__ import annotations

import argparse
import hashlib
from dataclasses import dataclass
from pathlib import Path


ROM_SIZE = 128 * 1024
WIDTH = 224
HEIGHT = 144
FRAME_SIZE = WIDTH * HEIGHT * 3

INSIDE = "inside"
OUTSIDE = "outside"
VARIANTS = (INSIDE, OUTSIDE)
ROM_NAMES = {
    INSIDE: "wsc_window_inside_probe.wsc",
    OUTSIDE: "wsc_window_outside_probe.wsc",
}

# Filled by the structural review after the generated bytes are finalized.
ROM_SHA256 = {
    INSIDE: "34eec5463b9eb3f9d0b1c030c2d6d23e710f0abed7ec6188a3700352ccad03cd",
    OUTSIDE: "ff1f0132454a8e192f09d80e53272a9f7468574dd811bbf5e1b602db2f017a75",
}
FRAME_SHA256 = {
    INSIDE: "0cb73b4a9726acdd0e2568a86fa74f5bb30a85022d73828852b1bf507b19fedb",
    OUTSIDE: "becf6f2a30ebceefee165fbf0e7978e079d9896a5595128c335aab8de4597f68",
}

PROGRAM_OFFSET = 0x10000
PAYLOAD_OFFSET = 0x10300
MARKER_OFFSET = 0x10500
PAYLOAD = b"".join(bytes((index * 0x11,)) * 32 for index in range(4))

WINDOW_LEFT = 64
WINDOW_TOP = 40
WINDOW_RIGHT = 159
WINDOW_BOTTOM = 103

BLUE = bytes((0, 0, 255))
RED = bytes((255, 0, 0))
GREEN = bytes((0, 255, 0))
MAGENTA = bytes((255, 0, 255))

INSIDE_SPRITES = ((63, 48), (153, 48), (80, 39), (80, 97))
OUTSIDE_SPRITES = ((63, 64), (153, 64), (104, 39), (104, 97))


@dataclass(frozen=True)
class Sample:
    name: str
    x: int
    y: int
    color: bytes


def _validate_variant(variant: str) -> None:
    if variant not in VARIANTS:
        raise ValueError(f"unsupported window-boundary variant: {variant!r}")


def inside_window(x: int, y: int) -> bool:
    """Return true at and between all four inclusive boundaries."""

    return (
        WINDOW_LEFT <= x <= WINDOW_RIGHT
        and WINDOW_TOP <= y <= WINDOW_BOTTOM
    )


def pixel(frame: bytes, x: int, y: int) -> bytes:
    offset = (y * WIDTH + x) * 3
    return frame[offset : offset + 3]


def expected_frame(variant: str) -> bytes:
    """Compose the exact stable frame from independent layer rules."""

    _validate_variant(variant)
    frame = bytearray(BLUE * (WIDTH * HEIGHT))

    for y in range(HEIGHT):
        for x in range(WIDTH):
            screen2_visible = inside_window(x, y) == (variant == INSIDE)
            if screen2_visible:
                offset = (y * WIDTH + x) * 3
                frame[offset : offset + 3] = RED

    # Diagnostic sprites are high-priority and pairwise disjoint.  Normal
    # descriptors admit inclusive-window pixels; inverse descriptors admit the
    # complement.  Transparent pixels do not occur in these solid tiles.
    for sprite_group, wanted_region, color in (
        (INSIDE_SPRITES, True, GREEN),
        (OUTSIDE_SPRITES, False, MAGENTA),
    ):
        for sprite_x, sprite_y in sprite_group:
            for y in range(sprite_y, sprite_y + 8):
                for x in range(sprite_x, sprite_x + 8):
                    if 0 <= x < WIDTH and 0 <= y < HEIGHT and inside_window(x, y) == wanted_region:
                        offset = (y * WIDTH + x) * 3
                        frame[offset : offset + 3] = color
    return bytes(frame)


def boundary_samples(variant: str) -> tuple[Sample, ...]:
    """Return independent named samples for both sides of every edge."""

    _validate_variant(variant)
    screen_inside = RED if variant == INSIDE else BLUE
    screen_outside = BLUE if variant == INSIDE else RED
    samples = [
        Sample("screen2-left-inclusive", 64, 80, screen_inside),
        Sample("screen2-left-adjacent-outside", 63, 80, screen_outside),
        Sample("screen2-right-inclusive", 159, 80, screen_inside),
        Sample("screen2-right-adjacent-outside", 160, 80, screen_outside),
        Sample("screen2-top-inclusive", 120, 40, screen_inside),
        Sample("screen2-top-adjacent-outside", 120, 39, screen_outside),
        Sample("screen2-bottom-inclusive", 120, 103, screen_inside),
        Sample("screen2-bottom-adjacent-outside", 120, 104, screen_outside),
    ]

    underlying_inside = screen_inside
    underlying_outside = screen_outside
    samples.extend(
        (
            Sample("sprite-inside-left-inclusive", 64, 51, GREEN),
            Sample("sprite-inside-left-rejected", 63, 51, underlying_outside),
            Sample("sprite-inside-right-inclusive", 159, 51, GREEN),
            Sample("sprite-inside-right-rejected", 160, 51, underlying_outside),
            Sample("sprite-inside-top-inclusive", 83, 40, GREEN),
            Sample("sprite-inside-top-rejected", 83, 39, underlying_outside),
            Sample("sprite-inside-bottom-inclusive", 83, 103, GREEN),
            Sample("sprite-inside-bottom-rejected", 83, 104, underlying_outside),
            Sample("sprite-outside-left-admitted", 63, 67, MAGENTA),
            Sample("sprite-outside-left-boundary-rejected", 64, 67, underlying_inside),
            Sample("sprite-outside-right-admitted", 160, 67, MAGENTA),
            Sample("sprite-outside-right-boundary-rejected", 159, 67, underlying_inside),
            Sample("sprite-outside-top-admitted", 107, 39, MAGENTA),
            Sample("sprite-outside-top-boundary-rejected", 107, 40, underlying_inside),
            Sample("sprite-outside-bottom-admitted", 107, 104, MAGENTA),
            Sample("sprite-outside-bottom-boundary-rejected", 107, 103, underlying_inside),
        )
    )
    return tuple(samples)


def verify_rom(path: Path, variant: str) -> bytes:
    _validate_variant(variant)
    data = path.read_bytes()
    digest = hashlib.sha256(data).hexdigest()
    wanted_digest = ROM_SHA256[variant]
    if wanted_digest == "TO-BE-PINNED":
        raise AssertionError("window-boundary ROM identities have not been pinned")
    if len(data) != ROM_SIZE or digest != wanted_digest:
        raise ValueError(f"{variant} ROM size/hash mismatch: size={len(data)} sha256={digest}")

    identity = f"SWANSONG-WSC-WINDOW-{variant.upper()}-V1\0".encode("ascii")
    offsets = [index for index in range(len(data)) if data.startswith(identity, index)]
    if offsets != [MARKER_OFFSET]:
        raise ValueError(f"{variant} ROM marker offsets mismatch: {offsets}")
    if data[PAYLOAD_OFFSET : PAYLOAD_OFFSET + len(PAYLOAD)] != PAYLOAD:
        raise ValueError(f"{variant} ROM tile payload mismatch")

    game_id = 0x46 if variant == INSIDE else 0x47
    expected_footer = bytes((0xEA, 0, 0, 0, 0xF0, 0, 0, 1, game_id, 1, 0, 0, 4, 0))
    if data[-16:-2] != expected_footer:
        raise ValueError(f"{variant} ROM footer metadata mismatch")
    if int.from_bytes(data[-2:], "little") != sum(data[:-2]) & 0xFFFF:
        raise ValueError(f"{variant} ROM footer checksum mismatch")
    return data


def verify_frame(path: Path, variant: str) -> bytes:
    _validate_variant(variant)
    frame = path.read_bytes()
    if len(frame) != FRAME_SIZE:
        raise ValueError(f"{variant} frame size mismatch: {len(frame)} != {FRAME_SIZE}")

    for sample in boundary_samples(variant):
        actual = pixel(frame, sample.x, sample.y)
        if actual != sample.color:
            raise ValueError(
                f"{variant} {sample.name} pixel ({sample.x},{sample.y}) is "
                f"{actual.hex()}, expected {sample.color.hex()}"
            )

    digest = hashlib.sha256(frame).hexdigest()
    wanted_digest = FRAME_SHA256[variant]
    if wanted_digest == "TO-BE-PINNED":
        raise AssertionError("window-boundary frame identities have not been pinned")
    if digest != wanted_digest or frame != expected_frame(variant):
        raise ValueError(f"{variant} whole stable frame mismatch: sha256={digest}")
    return frame


def verify_pair(rom: Path, frame: Path, variant: str) -> dict[str, int]:
    verify_rom(rom, variant)
    verify_frame(frame, variant)
    expected = expected_frame(variant)
    return {
        "boundary_samples": len(boundary_samples(variant)),
        "inclusive_edges": 4,
        "sprites": 8,
        "diagnostic_pixels": sum(
            pixel(expected, x, y) in (GREEN, MAGENTA)
            for y in range(HEIGHT)
            for x in range(WIDTH)
        ),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--variant", choices=VARIANTS, required=True)
    parser.add_argument("--rom", type=Path, required=True)
    parser.add_argument("--frame", type=Path, required=True)
    args = parser.parse_args()
    try:
        counts = verify_pair(args.rom, args.frame, args.variant)
    except (OSError, ValueError) as error:
        raise SystemExit(f"window-boundary probe: {error}") from error
    print(
        f"PASS window-boundary {args.variant} "
        + " ".join(f"{name}={value}" for name, value in counts.items())
    )


if __name__ == "__main__":
    main()
