// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Regionally Famous contributors

#include "music.h"

#define N { DIALBUG_NOTE_NONE, 0, 0, 0 }
#define OFF { DIALBUG_NOTE_OFF, 0, 0, 0 }
#define EV(note_, instrument_, volume_, gate_) \
	{ (note_), (instrument_), (volume_), (gate_) }
#define ROW(ch1, ch2, ch3, ch4) { ch1, ch2, ch3, ch4 }

/* Original four-channel soundtrack. Each pattern is a 16-row grid; omitted
 * rows are holds. Songs reuse patterns through an eight-entry order list,
 * echoing Humming Cat's compact score/loop model without copying its data. */
const dialbug_pattern_t __far dialbug_patterns[] = {
	/* 0: BATTERY GLOW / A */
	{ .row = {
		[0]  = ROW(EV(E(5), DIALBUG_INST_LEAD, 14, 2), EV(E(2), DIALBUG_INST_BASS, 13, 4), EV(E(4), DIALBUG_INST_ARP_MINOR, 10, 4), EV(C(3), DIALBUG_INST_KICK, 15, 1)),
		[2]  = ROW(EV(G(5), DIALBUG_INST_LEAD, 13, 2), N, N, EV(C(5), DIALBUG_INST_HAT, 8, 1)),
		[4]  = ROW(EV(B(5), DIALBUG_INST_LEAD, 14, 3), EV(C(3), DIALBUG_INST_BASS, 12, 4), EV(C(4), DIALBUG_INST_ARP_MAJOR, 9, 4), EV(C(5), DIALBUG_INST_SNARE, 13, 1)),
		[6]  = ROW(EV(A(5), DIALBUG_INST_LEAD, 12, 2), N, N, EV(C(6), DIALBUG_INST_HAT, 7, 1)),
		[8]  = ROW(EV(G(5), DIALBUG_INST_LEAD, 13, 2), EV(D(3), DIALBUG_INST_BASS, 13, 4), EV(D(4), DIALBUG_INST_ARP_MAJOR, 9, 4), EV(C(3), DIALBUG_INST_KICK, 15, 1)),
		[10] = ROW(EV(FS(5), DIALBUG_INST_LEAD, 12, 2), N, N, EV(C(5), DIALBUG_INST_HAT, 8, 1)),
		[12] = ROW(EV(D(5), DIALBUG_INST_LEAD, 13, 2), EV(B(2), DIALBUG_INST_BASS, 12, 4), EV(B(3), DIALBUG_INST_ARP_MINOR, 10, 4), EV(C(5), DIALBUG_INST_SNARE, 13, 1)),
		[14] = ROW(EV(FS(5), DIALBUG_INST_LEAD, 12, 1), N, N, EV(C(6), DIALBUG_INST_HAT, 8, 1)),
		[15] = ROW(EV(D(6), DIALBUG_INST_LEAD, 14, 1), N, N, N)
	} },

	/* 1: BATTERY GLOW / B */
	{ .row = {
		[0]  = ROW(EV(B(5), DIALBUG_INST_PLUCK, 15, 2), EV(E(2), DIALBUG_INST_BASS, 14, 4), EV(E(4), DIALBUG_INST_ARP_MINOR, 11, 4), EV(C(3), DIALBUG_INST_KICK, 15, 1)),
		[2]  = ROW(EV(D(6), DIALBUG_INST_PLUCK, 14, 2), N, N, EV(C(6), DIALBUG_INST_HAT, 9, 1)),
		[4]  = ROW(EV(E(6), DIALBUG_INST_LEAD, 15, 2), EV(G(2), DIALBUG_INST_BASS, 13, 4), EV(G(4), DIALBUG_INST_ARP_MAJOR, 10, 4), EV(C(5), DIALBUG_INST_SNARE, 14, 1)),
		[6]  = ROW(EV(D(6), DIALBUG_INST_LEAD, 13, 2), N, N, EV(C(6), DIALBUG_INST_HAT, 8, 1)),
		[8]  = ROW(EV(A(5), DIALBUG_INST_PLUCK, 14, 2), EV(D(3), DIALBUG_INST_BASS, 14, 4), EV(D(4), DIALBUG_INST_ARP_MAJOR, 10, 4), EV(C(3), DIALBUG_INST_KICK, 15, 1)),
		[10] = ROW(EV(FS(5), DIALBUG_INST_PLUCK, 13, 2), N, N, EV(C(5), DIALBUG_INST_HAT, 9, 1)),
		[12] = ROW(EV(E(5), DIALBUG_INST_LEAD, 14, 2), EV(A(2), DIALBUG_INST_BASS, 13, 4), EV(A(3), DIALBUG_INST_ARP_MINOR, 10, 4), EV(C(5), DIALBUG_INST_SNARE, 14, 1)),
		[14] = ROW(EV(G(5), DIALBUG_INST_LEAD, 13, 1), N, N, EV(C(6), DIALBUG_INST_HAT, 9, 1)),
		[15] = ROW(EV(B(5), DIALBUG_INST_LEAD, 15, 1), N, N, EV(C(6), DIALBUG_INST_HAT, 7, 1))
	} },

	/* 2: BATTERY GLOW / turn-around */
	{ .row = {
		[0]  = ROW(EV(E(6), DIALBUG_INST_SAW, 14, 2), EV(E(2), DIALBUG_INST_BASS, 14, 4), EV(E(4), DIALBUG_INST_ARP_MINOR, 10, 4), EV(C(3), DIALBUG_INST_KICK, 15, 1)),
		[2]  = ROW(EV(D(6), DIALBUG_INST_SAW, 13, 2), N, N, EV(C(5), DIALBUG_INST_HAT, 9, 1)),
		[4]  = ROW(EV(B(5), DIALBUG_INST_SAW, 13, 2), EV(C(3), DIALBUG_INST_BASS, 13, 4), EV(C(4), DIALBUG_INST_ARP_MAJOR, 9, 4), EV(C(5), DIALBUG_INST_SNARE, 14, 1)),
		[6]  = ROW(EV(A(5), DIALBUG_INST_SAW, 12, 2), N, N, EV(C(6), DIALBUG_INST_HAT, 9, 1)),
		[8]  = ROW(EV(G(5), DIALBUG_INST_SAW, 13, 2), EV(D(3), DIALBUG_INST_BASS, 14, 4), EV(D(4), DIALBUG_INST_ARP_MAJOR, 10, 4), EV(C(3), DIALBUG_INST_KICK, 15, 1)),
		[10] = ROW(EV(FS(5), DIALBUG_INST_SAW, 12, 2), N, N, EV(C(5), DIALBUG_INST_HAT, 9, 1)),
		[12] = ROW(EV(E(5), DIALBUG_INST_LEAD, 14, 1), EV(B(2), DIALBUG_INST_BASS, 13, 4), EV(B(3), DIALBUG_INST_ARP_MINOR, 10, 4), EV(C(5), DIALBUG_INST_SNARE, 14, 1)),
		[13] = ROW(EV(FS(5), DIALBUG_INST_LEAD, 13, 1), N, N, EV(C(6), DIALBUG_INST_HAT, 8, 1)),
		[14] = ROW(EV(G(5), DIALBUG_INST_LEAD, 14, 1), N, N, EV(C(5), DIALBUG_INST_SNARE, 11, 1)),
		[15] = ROW(EV(B(5), DIALBUG_INST_LEAD, 15, 1), N, OFF, EV(C(6), DIALBUG_INST_HAT, 10, 1))
	} },

	/* 3: NEON RAINTRACE / A */
	{ .row = {
		[0]  = ROW(EV(G(4), DIALBUG_INST_PULSE, 14, 2), EV(C(2), DIALBUG_INST_BASS, 14, 4), EV(C(4), DIALBUG_INST_ARP_MINOR, 10, 4), EV(C(3), DIALBUG_INST_KICK, 15, 1)),
		[2]  = ROW(EV(C(5), DIALBUG_INST_PULSE, 13, 2), N, N, EV(C(6), DIALBUG_INST_HAT, 8, 1)),
		[4]  = ROW(EV(DS(5), DIALBUG_INST_PULSE, 14, 3), EV(GS(2), DIALBUG_INST_BASS, 13, 4), EV(GS(3), DIALBUG_INST_ARP_MAJOR, 9, 4), EV(C(5), DIALBUG_INST_SNARE, 13, 1)),
		[6]  = ROW(EV(C(5), DIALBUG_INST_PULSE, 12, 2), N, N, EV(C(6), DIALBUG_INST_HAT, 7, 1)),
		[8]  = ROW(EV(G(5), DIALBUG_INST_PULSE, 14, 2), EV(DS(2), DIALBUG_INST_BASS, 13, 4), EV(DS(4), DIALBUG_INST_ARP_MAJOR, 9, 4), EV(C(3), DIALBUG_INST_KICK, 15, 1)),
		[10] = ROW(EV(F(5), DIALBUG_INST_PULSE, 13, 2), N, N, EV(C(5), DIALBUG_INST_HAT, 8, 1)),
		[12] = ROW(EV(D(5), DIALBUG_INST_PULSE, 13, 2), EV(AS(2), DIALBUG_INST_BASS, 13, 4), EV(AS(3), DIALBUG_INST_ARP_MAJOR, 9, 4), EV(C(5), DIALBUG_INST_SNARE, 13, 1)),
		[14] = ROW(EV(C(5), DIALBUG_INST_PULSE, 14, 2), N, N, EV(C(6), DIALBUG_INST_HAT, 8, 1))
	} },

	/* 4: NEON RAINTRACE / B */
	{ .row = {
		[0]  = ROW(EV(C(5), DIALBUG_INST_BELL, 15, 2), EV(F(2), DIALBUG_INST_BASS, 13, 4), EV(F(3), DIALBUG_INST_ARP_MINOR, 10, 4), EV(C(3), DIALBUG_INST_KICK, 15, 1)),
		[2]  = ROW(EV(G(5), DIALBUG_INST_BELL, 13, 2), N, N, EV(C(6), DIALBUG_INST_HAT, 8, 1)),
		[4]  = ROW(EV(GS(5), DIALBUG_INST_BELL, 14, 2), EV(GS(2), DIALBUG_INST_BASS, 13, 4), EV(GS(3), DIALBUG_INST_ARP_MAJOR, 9, 4), EV(C(5), DIALBUG_INST_SNARE, 14, 1)),
		[6]  = ROW(EV(G(5), DIALBUG_INST_BELL, 12, 2), N, N, EV(C(6), DIALBUG_INST_HAT, 8, 1)),
		[8]  = ROW(EV(DS(5), DIALBUG_INST_PULSE, 14, 2), EV(C(3), DIALBUG_INST_BASS, 14, 4), EV(C(4), DIALBUG_INST_ARP_MINOR, 10, 4), EV(C(3), DIALBUG_INST_KICK, 15, 1)),
		[10] = ROW(EV(C(5), DIALBUG_INST_PULSE, 13, 2), N, N, EV(C(5), DIALBUG_INST_HAT, 9, 1)),
		[12] = ROW(EV(D(5), DIALBUG_INST_PULSE, 13, 2), EV(G(2), DIALBUG_INST_BASS, 13, 4), EV(G(3), DIALBUG_INST_ARP_MAJOR, 9, 4), EV(C(5), DIALBUG_INST_SNARE, 14, 1)),
		[14] = ROW(EV(G(5), DIALBUG_INST_PULSE, 14, 1), N, N, EV(C(6), DIALBUG_INST_HAT, 9, 1)),
		[15] = ROW(EV(AS(5), DIALBUG_INST_PULSE, 13, 1), N, N, N)
	} },

	/* 5: NEON RAINTRACE / sign-off */
	{ .row = {
		[0]  = ROW(EV(C(6), DIALBUG_INST_PULSE, 15, 2), EV(C(2), DIALBUG_INST_BASS, 14, 4), EV(C(4), DIALBUG_INST_ARP_MINOR, 11, 4), EV(C(3), DIALBUG_INST_KICK, 15, 1)),
		[2]  = ROW(EV(AS(5), DIALBUG_INST_PULSE, 13, 2), N, N, EV(C(6), DIALBUG_INST_HAT, 9, 1)),
		[4]  = ROW(EV(GS(5), DIALBUG_INST_PULSE, 13, 2), EV(GS(2), DIALBUG_INST_BASS, 13, 4), EV(GS(3), DIALBUG_INST_ARP_MAJOR, 9, 4), EV(C(5), DIALBUG_INST_SNARE, 14, 1)),
		[6]  = ROW(EV(G(5), DIALBUG_INST_PULSE, 12, 2), N, N, EV(C(6), DIALBUG_INST_HAT, 9, 1)),
		[8]  = ROW(EV(F(5), DIALBUG_INST_BELL, 13, 2), EV(AS(2), DIALBUG_INST_BASS, 13, 4), EV(AS(3), DIALBUG_INST_ARP_MAJOR, 9, 4), EV(C(3), DIALBUG_INST_KICK, 15, 1)),
		[10] = ROW(EV(DS(5), DIALBUG_INST_BELL, 13, 2), N, N, EV(C(5), DIALBUG_INST_HAT, 9, 1)),
		[12] = ROW(EV(D(5), DIALBUG_INST_PULSE, 13, 1), EV(G(2), DIALBUG_INST_BASS, 13, 4), EV(G(3), DIALBUG_INST_ARP_MAJOR, 9, 4), EV(C(5), DIALBUG_INST_SNARE, 14, 1)),
		[13] = ROW(EV(DS(5), DIALBUG_INST_PULSE, 13, 1), N, N, EV(C(6), DIALBUG_INST_HAT, 8, 1)),
		[14] = ROW(EV(G(5), DIALBUG_INST_PULSE, 14, 1), N, N, EV(C(5), DIALBUG_INST_SNARE, 11, 1)),
		[15] = ROW(EV(C(6), DIALBUG_INST_PULSE, 15, 1), N, OFF, EV(C(6), DIALBUG_INST_HAT, 10, 1))
	} },

	/* 6: SOFT RESET SUNRISE / A */
	{ .row = {
		[0]  = ROW(EV(A(4), DIALBUG_INST_BELL, 13, 4), EV(F(2), DIALBUG_INST_BASS, 11, 8), EV(F(3), DIALBUG_INST_PAD, 8, 8), EV(C(3), DIALBUG_INST_KICK, 11, 1)),
		[2]  = ROW(N, N, N, EV(C(6), DIALBUG_INST_HAT, 5, 1)),
		[4]  = ROW(EV(C(5), DIALBUG_INST_BELL, 13, 4), N, N, EV(C(5), DIALBUG_INST_SNARE, 8, 1)),
		[6]  = ROW(N, N, N, EV(C(6), DIALBUG_INST_HAT, 5, 1)),
		[8]  = ROW(EV(F(5), DIALBUG_INST_BELL, 14, 4), EV(D(2), DIALBUG_INST_BASS, 11, 8), EV(D(3), DIALBUG_INST_PAD, 8, 8), EV(C(3), DIALBUG_INST_KICK, 11, 1)),
		[10] = ROW(N, N, N, EV(C(6), DIALBUG_INST_HAT, 5, 1)),
		[12] = ROW(EV(E(5), DIALBUG_INST_BELL, 12, 4), N, N, EV(C(5), DIALBUG_INST_SNARE, 8, 1)),
		[14] = ROW(EV(C(5), DIALBUG_INST_BELL, 11, 2), N, N, EV(C(6), DIALBUG_INST_HAT, 5, 1))
	} },

	/* 7: SOFT RESET SUNRISE / B */
	{ .row = {
		[0]  = ROW(EV(D(5), DIALBUG_INST_BELL, 13, 4), EV(AS(2), DIALBUG_INST_BASS, 11, 8), EV(AS(3), DIALBUG_INST_PAD, 8, 8), EV(C(3), DIALBUG_INST_KICK, 11, 1)),
		[2]  = ROW(N, N, N, EV(C(6), DIALBUG_INST_HAT, 5, 1)),
		[4]  = ROW(EV(F(5), DIALBUG_INST_BELL, 13, 4), N, N, EV(C(5), DIALBUG_INST_SNARE, 8, 1)),
		[6]  = ROW(EV(G(5), DIALBUG_INST_BELL, 11, 2), N, N, EV(C(6), DIALBUG_INST_HAT, 5, 1)),
		[8]  = ROW(EV(E(5), DIALBUG_INST_BELL, 13, 4), EV(C(3), DIALBUG_INST_BASS, 11, 8), EV(C(4), DIALBUG_INST_PAD, 8, 8), EV(C(3), DIALBUG_INST_KICK, 11, 1)),
		[10] = ROW(N, N, N, EV(C(6), DIALBUG_INST_HAT, 5, 1)),
		[12] = ROW(EV(C(5), DIALBUG_INST_BELL, 12, 2), N, N, EV(C(5), DIALBUG_INST_SNARE, 8, 1)),
		[14] = ROW(EV(G(4), DIALBUG_INST_BELL, 11, 2), N, N, EV(C(6), DIALBUG_INST_HAT, 5, 1))
	} },

	/* 8: SOFT RESET SUNRISE / horizon */
	{ .row = {
		[0]  = ROW(EV(F(5), DIALBUG_INST_BELL, 14, 4), EV(F(2), DIALBUG_INST_BASS, 12, 8), EV(F(3), DIALBUG_INST_PAD, 9, 8), EV(C(3), DIALBUG_INST_KICK, 11, 1)),
		[2]  = ROW(EV(A(5), DIALBUG_INST_BELL, 11, 2), N, N, EV(C(6), DIALBUG_INST_HAT, 5, 1)),
		[4]  = ROW(EV(G(5), DIALBUG_INST_BELL, 13, 4), N, N, EV(C(5), DIALBUG_INST_SNARE, 8, 1)),
		[6]  = ROW(EV(E(5), DIALBUG_INST_BELL, 11, 2), N, N, EV(C(6), DIALBUG_INST_HAT, 5, 1)),
		[8]  = ROW(EV(D(5), DIALBUG_INST_BELL, 13, 4), EV(AS(2), DIALBUG_INST_BASS, 11, 8), EV(AS(3), DIALBUG_INST_PAD, 8, 8), EV(C(3), DIALBUG_INST_KICK, 11, 1)),
		[10] = ROW(EV(F(5), DIALBUG_INST_BELL, 11, 2), N, N, EV(C(6), DIALBUG_INST_HAT, 5, 1)),
		[12] = ROW(EV(C(5), DIALBUG_INST_BELL, 12, 2), EV(C(3), DIALBUG_INST_BASS, 11, 4), EV(C(4), DIALBUG_INST_ARP_MAJOR, 7, 4), EV(C(5), DIALBUG_INST_SNARE, 8, 1)),
		[14] = ROW(EV(G(4), DIALBUG_INST_BELL, 10, 1), N, N, EV(C(6), DIALBUG_INST_HAT, 5, 1)),
		[15] = ROW(EV(C(5), DIALBUG_INST_BELL, 12, 1), N, OFF, N)
	} },

	/* 9: LAST SAVE POINT / A */
	{ .row = {
		[0]  = ROW(EV(A(4), DIALBUG_INST_SAW, 14, 2), EV(A(2), DIALBUG_INST_BASS, 14, 4), EV(A(3), DIALBUG_INST_ARP_MINOR, 11, 4), EV(C(3), DIALBUG_INST_KICK, 15, 1)),
		[2]  = ROW(EV(C(5), DIALBUG_INST_SAW, 13, 2), N, N, EV(C(6), DIALBUG_INST_HAT, 10, 1)),
		[4]  = ROW(EV(E(5), DIALBUG_INST_SAW, 15, 2), EV(F(2), DIALBUG_INST_BASS, 13, 4), EV(F(3), DIALBUG_INST_ARP_MAJOR, 10, 4), EV(C(5), DIALBUG_INST_SNARE, 15, 1)),
		[6]  = ROW(EV(F(5), DIALBUG_INST_SAW, 13, 2), N, N, EV(C(6), DIALBUG_INST_HAT, 9, 1)),
		[8]  = ROW(EV(E(5), DIALBUG_INST_SAW, 14, 2), EV(C(3), DIALBUG_INST_BASS, 14, 4), EV(C(4), DIALBUG_INST_ARP_MAJOR, 10, 4), EV(C(3), DIALBUG_INST_KICK, 15, 1)),
		[10] = ROW(EV(C(5), DIALBUG_INST_SAW, 13, 2), N, N, EV(C(5), DIALBUG_INST_HAT, 10, 1)),
		[12] = ROW(EV(G(4), DIALBUG_INST_SAW, 14, 2), EV(G(2), DIALBUG_INST_BASS, 13, 4), EV(G(3), DIALBUG_INST_ARP_MAJOR, 10, 4), EV(C(5), DIALBUG_INST_SNARE, 15, 1)),
		[14] = ROW(EV(B(4), DIALBUG_INST_SAW, 13, 2), N, N, EV(C(6), DIALBUG_INST_HAT, 9, 1))
	} },

	/* 10: LAST SAVE POINT / B */
	{ .row = {
		[0]  = ROW(EV(E(5), DIALBUG_INST_LEAD, 15, 2), EV(A(2), DIALBUG_INST_BASS, 14, 4), EV(A(3), DIALBUG_INST_ARP_MINOR, 11, 4), EV(C(3), DIALBUG_INST_KICK, 15, 1)),
		[2]  = ROW(EV(A(5), DIALBUG_INST_LEAD, 14, 2), N, N, EV(C(6), DIALBUG_INST_HAT, 10, 1)),
		[4]  = ROW(EV(G(5), DIALBUG_INST_LEAD, 14, 2), EV(F(2), DIALBUG_INST_BASS, 13, 4), EV(F(3), DIALBUG_INST_ARP_MAJOR, 10, 4), EV(C(5), DIALBUG_INST_SNARE, 15, 1)),
		[6]  = ROW(EV(E(5), DIALBUG_INST_LEAD, 13, 2), N, N, EV(C(6), DIALBUG_INST_HAT, 9, 1)),
		[8]  = ROW(EV(D(5), DIALBUG_INST_PLUCK, 14, 2), EV(D(3), DIALBUG_INST_BASS, 14, 4), EV(D(4), DIALBUG_INST_ARP_MINOR, 10, 4), EV(C(3), DIALBUG_INST_KICK, 15, 1)),
		[10] = ROW(EV(F(5), DIALBUG_INST_PLUCK, 13, 2), N, N, EV(C(5), DIALBUG_INST_HAT, 10, 1)),
		[12] = ROW(EV(E(5), DIALBUG_INST_LEAD, 14, 2), EV(E(3), DIALBUG_INST_BASS, 13, 4), EV(E(4), DIALBUG_INST_ARP_MAJOR, 10, 4), EV(C(5), DIALBUG_INST_SNARE, 15, 1)),
		[14] = ROW(EV(B(4), DIALBUG_INST_LEAD, 13, 1), N, N, EV(C(6), DIALBUG_INST_HAT, 9, 1)),
		[15] = ROW(EV(GS(5), DIALBUG_INST_LEAD, 14, 1), N, N, EV(C(6), DIALBUG_INST_HAT, 8, 1))
	} },

	/* 11: LAST SAVE POINT / continue? */
	{ .row = {
		[0]  = ROW(EV(A(5), DIALBUG_INST_SAW, 15, 2), EV(A(2), DIALBUG_INST_BASS, 14, 4), EV(A(3), DIALBUG_INST_ARP_MINOR, 11, 4), EV(C(3), DIALBUG_INST_KICK, 15, 1)),
		[2]  = ROW(EV(G(5), DIALBUG_INST_SAW, 13, 2), N, N, EV(C(6), DIALBUG_INST_HAT, 10, 1)),
		[4]  = ROW(EV(E(5), DIALBUG_INST_SAW, 14, 2), EV(F(2), DIALBUG_INST_BASS, 13, 4), EV(F(3), DIALBUG_INST_ARP_MAJOR, 10, 4), EV(C(5), DIALBUG_INST_SNARE, 15, 1)),
		[6]  = ROW(EV(C(5), DIALBUG_INST_SAW, 13, 2), N, N, EV(C(6), DIALBUG_INST_HAT, 10, 1)),
		[8]  = ROW(EV(D(5), DIALBUG_INST_PLUCK, 14, 2), EV(D(3), DIALBUG_INST_BASS, 14, 4), EV(D(4), DIALBUG_INST_ARP_MINOR, 10, 4), EV(C(3), DIALBUG_INST_KICK, 15, 1)),
		[10] = ROW(EV(E(5), DIALBUG_INST_PLUCK, 13, 2), N, N, EV(C(5), DIALBUG_INST_HAT, 10, 1)),
		[12] = ROW(EV(G(5), DIALBUG_INST_LEAD, 14, 1), EV(E(3), DIALBUG_INST_BASS, 13, 4), EV(E(4), DIALBUG_INST_ARP_MAJOR, 10, 4), EV(C(5), DIALBUG_INST_SNARE, 15, 1)),
		[13] = ROW(EV(A(5), DIALBUG_INST_LEAD, 14, 1), N, N, EV(C(6), DIALBUG_INST_HAT, 9, 1)),
		[14] = ROW(EV(B(5), DIALBUG_INST_LEAD, 15, 1), N, N, EV(C(5), DIALBUG_INST_SNARE, 12, 1)),
		[15] = ROW(EV(E(6), DIALBUG_INST_LEAD, 15, 1), N, OFF, EV(C(6), DIALBUG_INST_HAT, 11, 1))
	} },

	/* 12: SIGNAL BLOOM / A - E minor, rising channel-3 sweep replies */
	{ .row = {
		[0]  = ROW(EV(E(5), DIALBUG_INST_PLUCK, 14, 2), EV(E(2), DIALBUG_INST_BASS, 13, 4), EV(B(4), DIALBUG_INST_SWEEP, 10, 3), EV(C(3), DIALBUG_INST_KICK, 15, 1)),
		[2]  = ROW(N, N, N, EV(C(6), DIALBUG_INST_HAT, 8, 1)),
		[3]  = ROW(EV(G(5), DIALBUG_INST_PLUCK, 13, 2), N, N, N),
		[4]  = ROW(N, EV(C(3), DIALBUG_INST_BASS, 12, 4), EV(G(4), DIALBUG_INST_SWEEP, 9, 3), EV(C(5), DIALBUG_INST_SNARE, 13, 1)),
		[6]  = ROW(EV(B(5), DIALBUG_INST_PLUCK, 14, 2), N, N, EV(C(6), DIALBUG_INST_HAT, 8, 1)),
		[8]  = ROW(EV(A(5), DIALBUG_INST_LEAD, 13, 2), EV(G(2), DIALBUG_INST_BASS, 13, 4), EV(D(5), DIALBUG_INST_SWEEP, 10, 3), EV(C(3), DIALBUG_INST_KICK, 15, 1)),
		[10] = ROW(EV(G(5), DIALBUG_INST_LEAD, 12, 2), N, N, EV(C(6), DIALBUG_INST_HAT, 8, 1)),
		[12] = ROW(N, EV(D(3), DIALBUG_INST_BASS, 12, 4), EV(A(4), DIALBUG_INST_SWEEP, 9, 3), EV(C(5), DIALBUG_INST_SNARE, 13, 1)),
		[14] = ROW(EV(FS(5), DIALBUG_INST_PLUCK, 13, 1), N, N, EV(C(6), DIALBUG_INST_HAT, 9, 1)),
		[15] = ROW(EV(E(6), DIALBUG_INST_PLUCK, 14, 1), N, N, N)
	} },

	/* 13: SIGNAL BLOOM / B - wider contour and a darker second cadence */
	{ .row = {
		[0]  = ROW(EV(B(5), DIALBUG_INST_LEAD, 14, 2), EV(C(3), DIALBUG_INST_BASS, 13, 4), EV(E(5), DIALBUG_INST_SWEEP, 10, 3), EV(C(3), DIALBUG_INST_KICK, 15, 1)),
		[2]  = ROW(EV(D(6), DIALBUG_INST_LEAD, 13, 2), N, N, EV(C(6), DIALBUG_INST_HAT, 8, 1)),
		[4]  = ROW(EV(E(6), DIALBUG_INST_SAW, 14, 2), EV(A(2), DIALBUG_INST_BASS, 13, 4), EV(C(5), DIALBUG_INST_SWEEP, 9, 3), EV(C(5), DIALBUG_INST_SNARE, 14, 1)),
		[6]  = ROW(EV(D(6), DIALBUG_INST_SAW, 12, 2), N, N, EV(C(6), DIALBUG_INST_HAT, 8, 1)),
		[8]  = ROW(EV(B(5), DIALBUG_INST_PLUCK, 14, 2), EV(E(2), DIALBUG_INST_BASS, 13, 4), EV(B(4), DIALBUG_INST_SWEEP, 10, 3), EV(C(3), DIALBUG_INST_KICK, 15, 1)),
		[10] = ROW(EV(A(5), DIALBUG_INST_PLUCK, 13, 2), N, N, EV(C(6), DIALBUG_INST_HAT, 9, 1)),
		[11] = ROW(EV(G(5), DIALBUG_INST_PLUCK, 12, 1), N, N, N),
		[12] = ROW(N, EV(B(2), DIALBUG_INST_BASS, 13, 4), EV(FS(5), DIALBUG_INST_SWEEP, 9, 3), EV(C(5), DIALBUG_INST_SNARE, 14, 1)),
		[14] = ROW(EV(FS(5), DIALBUG_INST_LEAD, 13, 1), N, N, EV(C(6), DIALBUG_INST_HAT, 9, 1)),
		[15] = ROW(EV(B(5), DIALBUG_INST_LEAD, 14, 1), N, N, N)
	} },

	/* 14: SIGNAL BLOOM / handoff - descending signal, dominant pickup */
	{ .row = {
		[0]  = ROW(EV(G(5), DIALBUG_INST_BELL, 14, 2), EV(E(2), DIALBUG_INST_BASS, 13, 4), EV(B(4), DIALBUG_INST_SWEEP, 10, 3), EV(C(3), DIALBUG_INST_KICK, 15, 1)),
		[2]  = ROW(EV(FS(5), DIALBUG_INST_BELL, 12, 2), N, N, EV(C(6), DIALBUG_INST_HAT, 8, 1)),
		[4]  = ROW(EV(E(5), DIALBUG_INST_BELL, 13, 2), EV(D(3), DIALBUG_INST_BASS, 12, 4), EV(A(4), DIALBUG_INST_SWEEP, 9, 3), EV(C(5), DIALBUG_INST_SNARE, 13, 1)),
		[6]  = ROW(EV(D(5), DIALBUG_INST_BELL, 12, 2), N, N, EV(C(6), DIALBUG_INST_HAT, 8, 1)),
		[8]  = ROW(EV(C(5), DIALBUG_INST_PLUCK, 13, 2), EV(C(3), DIALBUG_INST_BASS, 12, 4), EV(G(4), DIALBUG_INST_SWEEP, 9, 3), EV(C(3), DIALBUG_INST_KICK, 15, 1)),
		[10] = ROW(EV(E(5), DIALBUG_INST_PLUCK, 13, 2), N, N, EV(C(6), DIALBUG_INST_HAT, 9, 1)),
		[12] = ROW(EV(DS(5), DIALBUG_INST_LEAD, 13, 1), EV(B(2), DIALBUG_INST_BASS, 13, 4), EV(FS(4), DIALBUG_INST_SWEEP, 10, 3), EV(C(5), DIALBUG_INST_SNARE, 14, 1)),
		[13] = ROW(EV(FS(5), DIALBUG_INST_LEAD, 13, 1), N, N, N),
		[14] = ROW(EV(B(5), DIALBUG_INST_LEAD, 14, 1), N, N, EV(C(6), DIALBUG_INST_HAT, 9, 1)),
		[15] = ROW(EV(D(6), DIALBUG_INST_LEAD, 14, 1), N, OFF, N)
	} }
};

const dialbug_song_t __far dialbug_songs[] = {
	{
		.title = "BATTERY GLOW",
		.subtitle = "battery-lit velocity",
		.bpm = 148,
		.order_length = 8,
		.order = { 0, 0, 1, 0, 1, 1, 0, 2 }
	},
	{
		.title = "NEON RAINTRACE",
		.subtitle = "rain on the cartridge bus",
		.bpm = 132,
		.order_length = 8,
		.order = { 3, 3, 4, 3, 4, 4, 3, 5 }
	},
	{
		.title = "SOFT RESET SUNRISE",
		.subtitle = "warm pixels at midnight",
		.bpm = 106,
		.order_length = 8,
		.order = { 6, 6, 7, 6, 7, 7, 6, 8 }
	},
	{
		.title = "LAST SAVE POINT",
		.subtitle = "continue? always",
		.bpm = 164,
		.order_length = 8,
		.order = { 9, 9, 10, 9, 10, 10, 9, 11 }
	},
	{
		.title = "SIGNAL BLOOM",
		.subtitle = "a reply from low orbit",
		.bpm = 140,
		.order_length = 8,
		.order = { 12, 12, 13, 12, 13, 13, 12, 14 }
	}
};

const uint8_t dialbug_song_count = (uint8_t)(sizeof(dialbug_songs) / sizeof(dialbug_songs[0]));
