#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Regionally Famous contributors
"""Normalize wf-process symbol order so clean ROM builds are reproducible."""

from __future__ import annotations

from pathlib import Path
import re
import sys


DEFINITION = re.compile(
    r"const uint8_t __wf_rom (?P<name>[A-Za-z0-9_]+)\[[0-9]+\] "
    r"__attribute__\(\(aligned\(2\)\)\) = \{\n.*?\n\};\n",
    re.DOTALL,
)


def main() -> int:
    if len(sys.argv) != 2:
        raise SystemExit("usage: normalize_wfprocess_c.py GENERATED.c")
    path = Path(sys.argv[1])
    text = path.read_text(encoding="utf-8")
    matches = list(DEFINITION.finditer(text))
    if not matches:
        raise SystemExit(f"no wf-process symbols found in {path}")

    preamble = text[: matches[0].start()]
    trailer = text[matches[-1].end() :]
    # wf-process stores emitted symbols in a Lua hash table. Sorting the
    # resulting definitions prevents hash iteration order from changing ELF
    # section placement and, consequently, otherwise identical ROM bytes.
    definitions = sorted(
        (match.group("name"), match.group(0)) for match in matches
    )
    preamble = re.sub(
        r"^// autogenerated by wf-process on .*?$",
        "// autogenerated by wf-process; symbol order normalized",
        preamble,
        count=1,
        flags=re.MULTILINE,
    )
    path.write_text(
        preamble + "".join(block for _, block in definitions) + trailer,
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
