#
# user core constraints
#
# put your clock groups in here as well as any net assignments
#

set_clock_groups -asynchronous \
 -group { bridge_spiclk } \
 -group { clk_74a } \
 -group { clk_74b } \
 -group { ic|mp1|mf_pllbase_inst|altera_pll_i|general[0].gpll~PLL_OUTPUT_COUNTER|divclk \
          ic|mp1|mf_pllbase_inst|altera_pll_i|general[1].gpll~PLL_OUTPUT_COUNTER|divclk \
          ic|mp1|mf_pllbase_inst|altera_pll_i|general[2].gpll~PLL_OUTPUT_COUNTER|divclk \
          ic|mp1|mf_pllbase_inst|altera_pll_i|general[3].gpll~PLL_OUTPUT_COUNTER|divclk }

# All four mp1 outputs are generated by one PLL.  In particular, the 36.864 MHz
# scan generator and 6.144 MHz Pocket video clock are exact phase-related 6:1
# clocks.  Keeping counters 2/3 in separate asynchronous groups hid the complete
# RGB/control transfer from TimeQuest.  The transfer is now staged on the
# falling edge of counter 1 and captured on counter 2; retain the generated-clock
# relationship so setup/hold analysis covers that half-system-cycle boundary.

# Pocket interact settings are an eleven-bit acknowledged bundled-data CDC.
# settings_hold_source is frozen before its request toggle enters the console-side
# synchronizer and remains frozen until settings_destination captures the whole
# package and acknowledges it. Bound both delay and skew so legal 01 <-> 10 menu
# transitions cannot be observed as a torn setting in the console domain.
set settings_source_registers [get_registers -nowarn -no_duplicates \
  {ic|settings_command_cdc|settings_hold_source[*]}]
set settings_destination_registers [get_registers -nowarn -no_duplicates \
  {ic|settings_command_cdc|settings_destination[*]}]

if {[get_collection_size $settings_source_registers] != 11} {
  error "settings CDC constraint expected 11 settings_hold_source registers"
}
if {[get_collection_size $settings_destination_registers] != 11} {
  error "settings CDC constraint expected 11 settings_destination registers"
}

set_net_delay -max \
  -get_value_from_clock_period dst_clock_period \
  -value_multiplier 1.0 \
  -from $settings_source_registers \
  -to $settings_destination_registers
set_max_skew \
  -get_skew_value_from_clock_period min_clock_period \
  -skew_value_multiplier 1.0 \
  -from $settings_source_registers \
  -to $settings_destination_registers

# Scaler selection is a two-bit acknowledged bundled-data CDC. slot_hold_sys
# is frozen before its request toggle crosses to the video clock and remains
# frozen until pending_slot_video captures it and returns an acknowledgement.
# Bound the payload independently so placement cannot spread its two bits over
# different destination captures.
set scaler_slot_source_registers [get_registers -nowarn -no_duplicates \
  {ic|scaler_selector|slot_hold_sys[*]}]
set scaler_slot_destination_registers [get_registers -nowarn -no_duplicates \
  {ic|scaler_selector|pending_slot_video[*]}]

if {[get_collection_size $scaler_slot_source_registers] != 2} {
  error "scaler slot CDC constraint expected 2 slot_hold_sys registers"
}
if {[get_collection_size $scaler_slot_destination_registers] != 2} {
  error "scaler slot CDC constraint expected 2 pending_slot_video registers"
}

set_net_delay -max \
  -get_value_from_clock_period dst_clock_period \
  -value_multiplier 1.0 \
  -from $scaler_slot_source_registers \
  -to $scaler_slot_destination_registers
set_max_skew \
  -get_skew_value_from_clock_period min_clock_period \
  -skew_value_multiplier 1.0 \
  -from $scaler_slot_source_registers \
  -to $scaler_slot_destination_registers

# Footer save metadata is a bundled-data CDC. metadata_hold is frozen before
# request_toggle enters the two-flop request_meta/request_sync chain and stays
# frozen until the acknowledgement returns. Keep the clocks asynchronous, but
# independently bound this exact 21-bit payload so it settles within one clk_74a
# period and its bits cannot spread across destination capture cycles.
set save_metadata_source_registers [get_registers -nowarn -no_duplicates \
  {ic|save_metadata_command_cdc|metadata_hold[*]}]
set save_metadata_destination_registers [get_registers -nowarn -no_duplicates \
  {ic|save_metadata_command_cdc|save_size_bytes_74a[*] \
   ic|save_metadata_command_cdc|has_rtc_74a}]

# Keep the exact logical collections above for fail-closed cardinality checks,
# but include any Fitter-generated register duplicates in the applied timing
# bounds. get_registers includes such duplicates unless -no_duplicates is set.
set save_metadata_source_registers_expanded [get_registers -nowarn \
  {ic|save_metadata_command_cdc|metadata_hold[*]}]
set save_metadata_destination_registers_expanded [get_registers -nowarn \
  {ic|save_metadata_command_cdc|save_size_bytes_74a[*] \
   ic|save_metadata_command_cdc|has_rtc_74a}]

# Fail closed if synthesis changes the intended hierarchy. An empty collection
# would otherwise leave this safety-critical bundled bus unconstrained.
proc swan_song_register_names {registers} {
  set names [list]
  foreach_in_collection register $registers {
    lappend names [get_object_info -name $register]
  }
  return [join [lsort $names] {, }]
}

set save_metadata_source_count \
  [get_collection_size $save_metadata_source_registers]
set save_metadata_destination_count \
  [get_collection_size $save_metadata_destination_registers]

if {$save_metadata_source_count != 21} {
  error "save metadata CDC constraint expected 21 metadata_hold registers; found $save_metadata_source_count register(s): [swan_song_register_names $save_metadata_source_registers]"
}
if {$save_metadata_destination_count != 21} {
  error "save metadata CDC constraint expected 21 destination registers; found $save_metadata_destination_count register(s): [swan_song_register_names $save_metadata_destination_registers]"
}

set_net_delay -max \
  -get_value_from_clock_period dst_clock_period \
  -value_multiplier 1.0 \
  -from $save_metadata_source_registers_expanded \
  -to $save_metadata_destination_registers_expanded
set_max_skew \
  -get_skew_value_from_clock_period min_clock_period \
  -skew_value_multiplier 1.0 \
  -from $save_metadata_source_registers_expanded \
  -to $save_metadata_destination_registers_expanded

derive_clock_uncertainty
